### ISSUE TITLE
Adopt interface to take OLHC data as numpy arrays

### ISSUE THREAD

**Issue by ronniec95** [jasonstrimpel/volatility-trading#1]
Altering the interface to allow for numpy arrays of olhc prices would extend the functionality to non-equity tickers.

**Comment by jasonstrimpel** [comment]
Do you mean abstracting the data from the vol estimator code to allow the user to use their own? The data is generated and manipulated in a Pandas.DataFrame at the moment.

**Comment by jasonstrimpel** [comment]
Hi the latest commit implements this functionality. Now either takes `pandas.DataFrame` or `numpy.ndarray` as inputs.
