### ISSUE TITLE
Question about the Value of Parkinson volatility estimator

### ISSUE THREAD

**Issue by Charlie9797** [jasonstrimpel/volatility-trading#10]
As Euan Sinclair said in the book "Volatility Trading", we could use Parkinson, RogersSatchell alternative volatility estimator instead of close-to-close volatility estimator and campare the implied volatility with these realized volitilties. However, I found that the Parkinson and RogersSatchell estimators are much larger than the implied volatility.(As is shown in the y-axis in the graphs, they are bigger than 100%, while the close-to-close estimator is more reasonable). 

I want to know if we could use alternative volatility estimators like Parkinson and compare the implied volatility with them to trade; or we must compare the the implied volatility with close-to-close volatility?

![Q2cc](https://user-images.githubusercontent.com/48789786/55533167-fa183980-56e2-11e9-8433-1241bd6521c5.png)
![Q1p](https://user-images.githubusercontent.com/48789786/55533172-fbe1fd00-56e2-11e9-9711-f6219f4b5ff9.png)
![Q3rs](https://user-images.githubusercontent.com/48789786/55533175-fd132a00-56e2-11e9-94d3-32c4d278080c.png)

**Comment by jasonstrimpel** [comment]
This isn't an issue (or question) about the code so closing.
