### ISSUE TITLE
The equation of volatility

### ISSUE THREAD

**Issue by ArronWang77** [jasonstrimpel/volatility-trading#12]
@jasonstrimpel Hi Jason, I find that the equation of GarmanKlass is different from that of RogersSatchell, as follows:

GarmanKlass:    return trading_periods * v.mean()**0.5
RogersSatchell:   return (trading_periods * v.mean())**0.5

Are you sure they are different? Thank you.

**Comment by thisisamirmaleki** [comment]
Parkinson formula also has the same problem, I'm fixing them both.

**Comment by thisisamirmaleki** [comment]
Check it out #20

**Comment by jasonstrimpel** [comment]
Thanks guys
