### ISSUE TITLE
Usage and application

### ISSUE THREAD

**Issue by sword134** [jasonstrimpel/volatility-trading#14]
Hello,
I've stumbled upon this library while looking for volatility models applicable to the stock market, however I'm a bit confused as to what the purpose of the repo is? Using a Parkinson estimator with SPY as benchmark and United States Steel Corp as the underlying symbol I get an R squared of 0.83. However looking through the code it appears that it is only fitting to the data and not doing any predictions.

My question is how do you apply the results that this repo gives in the real world and would it be correct to assume that these models can be used with the .predict() to get applicable results?

**Comment by jasonstrimpel** [comment]
This library provides historical volatility estimators. Of course you can use this historic results to predict but the onus is on you to interpret the results. I'm sorry for not answering but your question is a bit outside the scope of the code library itself. A great resource for this type of discussion is https://quant.stackexchange.com/.
