### ISSUE TITLE
k of Yang=Zhang estimator

### ISSUE THREAD

**Issue by evertontartari** [jasonstrimpel/volatility-trading#16]
Please, check line 34 on file YangZhang.py

Current code is
 k = 0.34 / (1 + (window + 1) / (window - 1))

I believe the code should be
 k = 0.34 / (1.34 + (window + 1) / (window - 1))

**Comment by jasonstrimpel** [comment]
Confirmed this from the original paper https://www.jstor.org/stable/10.1086/209650?seq=12#metadata_info_tab_contents
