### ISSUE TITLE
Unable to pip the library

### ISSUE THREAD

**Issue by investingbunny** [jasonstrimpel/volatility-trading#17]
Am I missing something?

(envy1) C:\Users\User>pip install volest
ERROR: Could not find a version that satisfies the requirement volest
ERROR: No matching distribution found for volest

(envy1) C:\Users\User>pip install volatility-trading
ERROR: Could not find a version that satisfies the requirement volatility-trading
ERROR: No matching distribution found for volatility-trading

**Comment by jasonstrimpel** [comment]
Yes this package does not exist in pip. You simply need to clone from github.
