### ISSUE TITLE
Garman and Klass code

### ISSUE THREAD

**Issue by bmanjare** [jasonstrimpel/volatility-trading#2]
log_hl = (prices['Adj High'] / prices['Adj Low']).apply(np.log)
log_co = (prices['Adj Close'] / prices['Adj Open']).apply(np.log)
log_oc = (prices['Adj Open'] / prices['Adj Close']).apply(np.log)

just wondering how this log_oc fits?

tried to modify the code as per book, i.e.
log_hl = (prices['Adj High'] / prices['Adj Low']).apply(np.log)
log_co = (prices['Adj Close'] / prices['Adj Close'].shift(1)).apply(np.log)

this returns, may be because of negative number:
return math.sqrt(252 \* v.mean())
ValueError: math domain error

Also, Rogers, Satchell, and Yoon works fine with following lines:
log_ho = (prices['Adj High'] / prices['Adj Open']).apply(np.log)
log_hc = (prices['Adj High'] / prices['Adj Close']).apply(np.log)
log_lo = (prices['Adj Low'] / prices['Adj Open']).apply(np.log)
log_lc = (prices['Adj Low'] / prices['Adj Close']).apply(np.log)

rs = log_hc \* log_ho + log_lc \* log_lo

**Comment by jasonstrimpel** [comment]
Resolved with latest commit.
