### ISSUE TITLE
AttributeError: 'Rectangle' Object Has No Property 'Normed' Solution

### ISSUE THREAD

**Issue by posidonius** [jasonstrimpel/volatility-trading#21]
Apparently [matplotlib no longer uses the "normed" property](https://stdworkflow.com/67/attributeerror-rectangle-object-has-no-property-normed-solution). This deprecated property appears in several places in this project, resulting in the error `AttributeError: 'Rectangle' Object Has No Property 'Normed' Solution`.

**Comment by will-riley** [comment]
Same problem here.

**Comment by jasonstrimpel** [comment]
Merged
