### ISSUE TITLE
math domain errors on some models 

### ISSUE THREAD

**Issue by alphaBenj** [jasonstrimpel/volatility-trading#3]
The models which follow def f(v) methods seem not to calculate the vols correctly.  

    17 
     18     def f(v):
---> 19         return math.sqrt(252 * v.mean())
     20 
     21     result = rs.rolling(window=window, center=False).apply(func=f)

ValueError: math domain error

**Comment by jasonstrimpel** [comment]
I realize I have no tests but can you give me the full code you used which is resulting in the error please? What symbol, dates... I need to replicate.

**Comment by alphaBenj** [comment]
can you email me newbox  dot me at gmail dot c0m. dont want to clutter repo.

**Comment by alphaBenj** [comment]
please connect via email... 
Where did  you source the equations for the Vol models, they are not of the standard form..
Can you include GKYKextension model?

Also, the ones which used  "def f(v):" all return results that were not close to results of Close-Close. 
-RogerSatchell,
-Parkinson
-GarmanKlass

In the zip, I hacked the data file to read local csv.. 
[volatilityRepo1.tar.gz](https://github.com/jasonstrimpel/volatility-trading/files/1026714/volatilityRepo1.tar.gz)

**Comment by jasonstrimpel** [comment]
Just post the code you're using to create error along with the error stacktrace.

**Comment by alphaBenj** [comment]
Its in the notebook in the zip!.... 


# call plt.show() on any of the below
fig, plt = vol.cones(windows=windows, quantiles=quantiles)
fig, plt = vol.rolling_quantiles(window=window, quantiles=quantiles)
fig, plt = vol.rolling_extremes(window=window)
fig, plt = vol.rolling_descriptives(window=window)
fig, plt = vol.histogram(window=window, bins=bins, normed=normed)
fig, plt = vol.benchmark_compare(window=window, bench=bench)
fig, plt = vol.benchmark_correlation(window=window, bench=bench)


# prints regression statistics
print vol.benchmark_regression(window=window, bench=bench)


# creates a pdf term sheet with all metrics
vol.term_sheet(window, windows, quantiles, bins, normed, bench)


ValueError                                Traceback (most recent call last)
<ipython-input-12-329042fe6743> in <module>()
      1 # call plt.show() on any of the below
----> 2 fig, plt = vol.cones(windows=windows, quantiles=quantiles)
      3 fig, plt = vol.rolling_quantiles(window=window, quantiles=quantiles)
      4 fig, plt = vol.rolling_extremes(window=window)
      5 fig, plt = vol.rolling_descriptives(window=window)

/home/ab10/virtEnvRVPYpersonal/volatilityRepo/volest.pyc in cones(self, windows, quantiles)
    130         for w in windows:
    131 
--> 132             estimator = self._get_estimator(w)
    133 
    134             max.append(estimator.max())

/home/ab10/virtEnvRVPYpersonal/volatilityRepo/volest.pyc in _get_estimator(self, window, symbol, clean)
     85 
     86         if self._estimator is "GarmanKlass":
---> 87             return models.GarmanKlass.get_estimator(symbol=symbol, start=self._start, end=self._end, window=window, clean=clean)
     88         elif self._estimator is "HodgesTompkins":
     89             return models.HodgesTompkins.get_estimator(symbol=symbol, start=self._start, end=self._end, window=window, clean=clean)

models/GarmanKlass.pyc in get_estimator(symbol, start, end, window, clean)
     19         return math.sqrt(252 * v.mean())
     20 
---> 21     result = rs.rolling(window=window, center=False).apply(func=f)
     22     result[:window-1] = np.nan
     23 

/usr/lib64/python2.7/site-packages/pandas/core/window.pyc in apply(self, func, args, kwargs)
   1082     @Appender(_shared_docs['apply'])
   1083     def apply(self, func, args=(), kwargs={}):
-> 1084         return super(Rolling, self).apply(func, args=args, kwargs=kwargs)
   1085 
   1086     @Substitution(name='rolling')

/usr/lib64/python2.7/site-packages/pandas/core/window.pyc in apply(self, func, args, kwargs)
    803 
    804         return self._apply(f, func, args=args, kwargs=kwargs,
--> 805                            center=False)
    806 
    807     def sum(self, *args, **kwargs):

/usr/lib64/python2.7/site-packages/pandas/core/window.pyc in _apply(self, func, name, window, center, check_minp, how, **kwargs)
    738                     result = np.apply_along_axis(calc, self.axis, values)
    739                 else:
--> 740                     result = calc(values)
    741 
    742             if center:

/usr/lib64/python2.7/site-packages/pandas/core/window.pyc in calc(x)
    732 
    733                 def calc(x):
--> 734                     return func(x, window, min_periods=self.min_periods)
    735 
    736             with np.errstate(all='ignore'):

/usr/lib64/python2.7/site-packages/pandas/core/window.pyc in f(arg, window, min_periods)
    800             return _window.roll_generic(arg, window, minp, indexi,
    801                                         offset, func, args,
--> 802                                         kwargs)
    803 
    804         return self._apply(f, func, args=args, kwargs=kwargs,

/pandas/window.pyx in pandas._window.roll_generic (pandas/window.c:35131)()

models/GarmanKlass.pyc in f(v)
     17 
     18     def f(v):
---> 19         return math.sqrt(252 * v.mean())
     20 
     21     result = rs.rolling(window=window, center=False).apply(func=f)

ValueError: math domain error

**Comment by alphaBenj** [comment]
check the zip, I hacked the data.py file to make a direct call to local *.csv

**Comment by jasonstrimpel** [comment]
Ah right because Yahoo changed their api so the pandas_datareader module has broken. The library now will not bring in any data. The community has not fixed the library yet. Once they do I will reimplement the vol library.

**Comment by jasonstrimpel** [comment]
Sorry I closed on accident. It may have something to do with Yahoo changing their API now the library I used to grab data is broken. Are you saying that when you import data direct from CSV there is no error?

**Comment by alphaBenj** [comment]
No, open the zip - it has the notebook and files need to replicate the bug.  

20
21 result = rs.rolling(window=window, center=False).apply(func=f)

ValueError: math domain error

**Comment by jasonstrimpel** [comment]
Sorry not opening a zip from a stranger. I'll take a look at the code. In the meantime, feel free to submit a pull request with a fix.

**Comment by alphaBenj** [comment]
take a look at my repo for this ... 
https://github.com/alphaBenj/fixVol

See the error here
https://github.com/alphaBenj/fixVol/blob/master/Volest-tester.ipynb

https://github.com/alphaBenj/fixVol/blob/master/data.py
line #34

Still would like to the sources of vols calculations.

**Comment by jasonstrimpel** [comment]
Ok thanks for that. I will be looking through the code over the weekend.

**Comment by jasonstrimpel** [comment]
The problem is your data set. The CSV has the adjusted close labeled as `Adj Close` and the non-adjusted close as `Close`. The adjusted close from the (broken) `YahooDailyReader` in `data.py` returns as `Close` which is what the estimator code looks for (you can see this in the docstring of the `data.py` file).

You are feeding in the non adjusted close field as the close which falls outside the `Low` and `High` range. This is creating negative mean fed to `sqrt` which as a result causes the domain error. If you change the `Adj Close` column to `Close` in your CSV you get the correct result.

This is not a bug.

**Comment by alphaBenj** [comment]
Still would like to the sources of vols calculations. What is the source of the way you calculate the vols.

**Comment by jasonstrimpel** [comment]
These are from Euan Sinclair's Volatility Trading. I used the Excel sheets included in the CD from the purchase of the book. This is mentioned as the first sentence on the README.md.

**Comment by alphaBenj** [comment]
You said they were based on, not sourced from CD. -- (fellow IIT-FMT grad.)

**Comment by jasonstrimpel** [comment]
CD was used for validation mate.

**Comment by MagicEthan** [comment]
This is possible. It depends on the dataset. See the issues I raised
