### ISSUE TITLE
GarmanKlass

### ISSUE THREAD

**Issue by MagicEthan** [jasonstrimpel/volatility-trading#4]
According to the original formula on the textbook, the codes should be revised as following:  

    # log_co = (price_data['Close'] / price_data['Open']).apply(np.log)
    log_cc = (price_data['Close'] / price_data['Close'].shift(1)).apply(np.log)

    rs = 0.5 * log_hl**2 - (2*math.log(2)-1) * log_cc**2 # Instead of log_co

Using today's close/open will underestimate the volatility caused by jump, however, if jumps always happen within a period, GarmanKlass will give a negative value to be rooted. Using the above formula based on the textbook:  

    def f(v):
        
        #print(245*v.mean())
        # return math.sqrt(252 * v.mean())
       
        return (245 * (v.mean()))
        # q = 245 * v.mean()
        # return q
        # return math.sqrt(v.mean())
        # return math.sqrt(245 * v.mean())
        # China Market has about 245 trading days
        # If we use intraday data, there should be 240 bars or more

we got:

![jpm](https://user-images.githubusercontent.com/11261402/30623449-3ce6339c-9dea-11e7-9f38-c9e9b6df9324.png)
![jpm_price](https://user-images.githubusercontent.com/11261402/30623450-3cf53de2-9dea-11e7-8081-a03075496f1d.png)

The second pic is JPM's price during June, 2016. We see that too many jumps result in a negative variance. But Jason's formula won't since abs(log(close/open)) is smaller.  

BTW, v ** (1/2) will not raise an error for a negative number while math.sqrt() does.

**Comment by jasonstrimpel** [comment]
Thanks please check.

**Comment by jasonstrimpel** [comment]
Thanks please check.
