### ISSUE TITLE
YangZhang

### ISSUE THREAD

**Issue by MagicEthan** [jasonstrimpel/volatility-trading#5]
If use different window other than 30 days, the following should be revised:

    # result = (open_vol + 0.164333 * close_vol + 0.835667 * window_rs).apply(np.sqrt) * math.sqrt(252)
    k = 0.34 / (1 + (window + 1) / (window - 1))
    result = (open_vol + k * close_vol + (1 - k) * window_rs).apply(np.sqrt) * math.sqrt(245)

We should use variables instead of constants.

**Comment by jasonstrimpel** [comment]
Thanks please check.

**Comment by yitelee** [comment]
According to the paper https://stockviz.biz/yang-zhang-volatility/
k should be calculated as:
k = 0.34 / (**1.34** + (window + 1) / (window - 1))
