### ISSUE TITLE
HodgesTompkins

### ISSUE THREAD

**Issue by MagicEthan** [jasonstrimpel/volatility-trading#6]
I feel that HT should be used in all other models, not only for adjusting close-to-close volatility. Overlapping data are used for all models when using rolling windows.

**Comment by MagicEthan** [comment]
Besides, the codes need to be revised:
```
    adj_factor = math.sqrt(
     (1.0 / (1.0 - (window / (log_return.count() - (window - 1.0))) +
              (window**2 - 1.0)/(3.0 * (log_return.count() - (window - 1.0))**2)))
```

        adj_factor = math.sqrt(
        1.0 / (1.0 - window / (result.count()) +
                (window**2 - 1.0)/(3.0 * (result.count()**2))))

This is the original formula on the textbook.

**Comment by jasonstrimpel** [comment]
Thanks please check.
